In [1]:
# pb 55
import numpy as np 
import pandas as pd
df=pd.DataFrame([["William",None,50000.0,42000.0],
                ["Emma","North",52000.0,43000.0],
                ["Sofia", "East",None,],
                ["Markus",None,None,None],
                ["YAYA","North",56000.0,65220.0],
                [None,None,None,None]],columns=["name","region",'sales','expances']
                )
print(df)
df_clean=df.dropna()
df_clean

      name region    sales  expances
0  William   None  50000.0   42000.0
1     Emma  North  52000.0   43000.0
2    Sofia   East      NaN       NaN
3   Markus   None      NaN       NaN
4     YAYA  North  56000.0   65220.0
5     None   None      NaN       NaN

   name region    sales  expances
1  Emma  North  52000.0   43000.0
4  YAYA  North  56000.0   65220.0

In [2]:
# Create a Pandas DataFrame from the following table and write code to
# remove all rows from this table only if all of their values 
# are NaN
df_allnun=df.dropna(how='all')
df_allnun

      name region    sales  expances
0  William   None  50000.0   42000.0
1     Emma  North  52000.0   43000.0
2    Sofia   East      NaN       NaN
3   Markus   None      NaN       NaN
4     YAYA  North  56000.0   65220.0

In [3]:
print(df.dropna())

   name region    sales  expances
1  Emma  North  52000.0   43000.0
4  YAYA  North  56000.0   65220.0

In [6]:
"""
Write Python code to remove outliers from any given DataFrame.
 Consider the following data:
data = {
    "A": ["TeamA", "TeamB", "TeamB", "TeamC", "TeamA"],
    "B": [50, 40, 40, 30, 50],
    "C": [True, False, False, False, True]
}
Convert this to a Pandas DataFrame and remove duplicate rows from it. Reset index values.
"""


data = {
    "A": ["TeamA", "TeamB", "TeamB", "TeamC", "TeamA"],
    "B": [50, 40, 40, 30, 50],
    "C": [True, False, False, False, True]
}
df2= pd.DataFrame(data)
df2.drop_duplicates().reset_index()

   index      A   B      C
0      0  TeamA  50   True
1      1  TeamB  40  False
2      3  TeamC  30  False

In [12]:

import pandas as pd
df = pd.DataFrame({
"ID": [101, 102, 103],
"Name": ["Amit", "Rahul", "Neha"],
"Marks": [78, 85, 92]
})
data=df.set_index("ID",inplace=True)

      Name  Marks
ID
101   Amit     78
102  Rahul     85
103   Neha     92